"""Production schema: tenancy, accounts, tax lots, orders, policy, jobs, audit chain

Revision ID: 3f8453b33b4d
Revises: 
Create Date: 2026-07-26 17:50:19.694092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8453b33b4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('as_of_date', sa.DateTime(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'as_of_date', name='uq_market_data_ticker_date')
    )
    with op.batch_alter_table('market_data_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_data_cache_as_of_date'), ['as_of_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_data_cache_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_data_cache_ticker'), ['ticker'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('default_policy', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange', sa.String(length=24), nullable=True),
    sa.Column('security_type', sa.String(length=24), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('avg_dollar_volume', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('forward_pe', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('ps_ratio', sa.Float(), nullable=True),
    sa.Column('peg_ratio', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('profit_margin', sa.Float(), nullable=True),
    sa.Column('return_on_equity', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('earnings_growth', sa.Float(), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('expense_ratio', sa.Float(), nullable=True),
    sa.Column('duration_years', sa.Float(), nullable=True),
    sa.Column('credit_quality', sa.String(length=16), nullable=True),
    sa.Column('momentum_6m', sa.Float(), nullable=True),
    sa.Column('momentum_12m', sa.Float(), nullable=True),
    sa.Column('volatility_1y', sa.Float(), nullable=True),
    sa.Column('max_drawdown_1y', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_restricted', sa.Boolean(), nullable=False),
    sa.Column('restriction_reason', sa.String(length=255), nullable=True),
    sa.Column('fundamentals_updated_at', sa.DateTime(), nullable=True),
    sa.Column('metrics_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("asset_class IN ('us_equity', 'intl_equity', 'em_equity', 'fixed_income', 'real_assets', 'commodity', 'cash', 'alternative')", name='ck_securities_asset_class'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_securities_asset_class'), ['asset_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_securities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_securities_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_securities_screen', ['is_active', 'asset_class', 'sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_securities_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_securities_ticker'), ['ticker'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'advisor', 'compliance', 'viewer')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'email', name='uq_users_org_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email_lookup', ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'advisor', 'compliance', 'viewer')", name='ck_api_keys_role'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_prefix'), ['prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_audit_org_time', ['org_id', 'occurred_at'], unique=False)

    op.create_table('client_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('risk_tolerance', sa.String(length=32), nullable=False),
    sa.Column('time_horizon_years', sa.Integer(), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('annual_income', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('liquidity_needs', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('kyc_status', sa.String(length=32), nullable=False),
    sa.Column('kyc_verified_at', sa.DateTime(), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_profiles_advisor_id'), ['advisor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_profiles_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_profiles_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_profiles_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_clients_org_active', ['org_id', 'deleted_at'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('tax_treatment', sa.String(length=32), nullable=False),
    sa.Column('custodian', sa.String(length=120), nullable=True),
    sa.Column('account_number_masked', sa.String(length=32), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('pending_cash_hold', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("account_type IN ('individual', 'joint', 'traditional_ira', 'roth_ira', '401k', 'trust', 'custodial')", name='ck_accounts_type'),
    sa.CheckConstraint("tax_treatment IN ('taxable', 'tax_deferred', 'tax_exempt')", name='ck_accounts_tax_treatment'),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_org_id'), ['org_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('node_name', sa.String(length=64), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('output_snapshot', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=80), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('policy_version', sa.Integer(), nullable=True),
    sa.Column('data_provenance', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'node_name', 'started_at', name='uq_agent_run_node_start')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_client_id'), ['client_id'], unique=False)
        batch_op.create_index('ix_agent_runs_client_time', ['client_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_run_id'), ['run_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_approvals_pending', ['run_id', 'decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_run_id'), ['run_id'], unique=False)

    op.create_table('investment_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('max_position_pct', sa.Float(), nullable=False),
    sa.Column('max_sector_pct', sa.Float(), nullable=False),
    sa.Column('max_asset_class_pct', sa.Float(), nullable=True),
    sa.Column('min_cash_pct', sa.Float(), nullable=False),
    sa.Column('max_cash_pct', sa.Float(), nullable=False),
    sa.Column('max_position_beta', sa.Float(), nullable=True),
    sa.Column('max_portfolio_beta', sa.Float(), nullable=True),
    sa.Column('min_market_cap', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('min_avg_dollar_volume', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('max_portfolio_volatility', sa.Float(), nullable=True),
    sa.Column('min_position_notional', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('target_allocation', sa.JSON(), nullable=False),
    sa.Column('drift_bands', sa.JSON(), nullable=False),
    sa.Column('allowed_asset_classes', sa.JSON(), nullable=False),
    sa.Column('excluded_tickers', sa.JSON(), nullable=False),
    sa.Column('excluded_sectors', sa.JSON(), nullable=False),
    sa.Column('lot_selection_method', sa.String(length=16), nullable=False),
    sa.Column('harvest_losses', sa.Boolean(), nullable=False),
    sa.Column('max_short_term_gain_budget', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('benchmark_ticker', sa.String(length=24), nullable=False),
    sa.Column('rebalance_frequency_days', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('draft','active','superseded')", name='ck_policy_status'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'version', name='uq_policy_client_version')
    )
    with op.batch_alter_table('investment_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_policies_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_policies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_policies_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_policy_active', ['client_id', 'status'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=48), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('current_step', sa.String(length=120), nullable=True),
    sa.Column('steps_total', sa.Integer(), nullable=True),
    sa.Column('steps_done', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=80), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled', 'timed_out')", name='ck_jobs_status'),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_claim', ['status', 'priority', 'queued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_heartbeat_at'), ['heartbeat_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_queued_at'), ['queued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('recommendation_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('recommended_at', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('was_executed', sa.Boolean(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('benchmark_return_pct', sa.Float(), nullable=True),
    sa.Column('excess_return_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'symbol', 'horizon_days', name='uq_outcome_run_symbol_horizon')
    )
    with op.batch_alter_table('recommendation_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_outcomes_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_outcomes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_outcomes_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_outcomes_recommended_at'), ['recommended_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_outcomes_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_outcomes_symbol'), ['symbol'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.Column('structured_payload', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approval_state', sa.String(length=16), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=True),
    sa.Column('llm_enabled', sa.Boolean(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('data_as_of', sa.DateTime(), nullable=True),
    sa.Column('disclosure_version', sa.String(length=16), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'version', name='uq_reports_run_version')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_run_id'), ['run_id'], unique=False)

    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_version', sa.String(length=16), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('capacity_score', sa.Float(), nullable=False),
    sa.Column('tolerance_score', sa.Float(), nullable=False),
    sa.Column('assigned_tier', sa.String(length=32), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('taken_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taken_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_org_id'), ['org_id'], unique=False)

    op.create_table('cash_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_transactions_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_transactions_org_id'), ['org_id'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cash_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('net_flow', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('holdings_snapshot', sa.JSON(), nullable=False),
    sa.Column('benchmark_ticker', sa.String(length=24), nullable=True),
    sa.Column('benchmark_close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'account_id', 'as_of', name='uq_snapshot_scope_date')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_org_id'), ['org_id'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'symbol', name='uq_positions_account_symbol')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_symbol'), ['symbol'], unique=False)

    op.create_table('trade_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('notional', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('current_weight', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('addresses_flaw', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('estimated_tax_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('blocked_reason', sa.String(length=500), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("side IN ('BUY', 'SELL')", name='ck_proposal_side'),
    sa.CheckConstraint("status IN ('proposed', 'approved', 'rejected', 'blocked', 'executed')", name='ck_proposal_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_proposals_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_proposals_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_proposals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_proposals_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_proposals_run_id'), ['run_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('time_in_force', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('average_fill_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("side IN ('BUY', 'SELL')", name='ck_orders_side'),
    sa.CheckConstraint("status IN ('draft', 'pending_approval', 'approved', 'rejected', 'submitted', 'filled', 'partially_filled', 'cancelled', 'failed', 'expired')", name='ck_orders_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['trade_proposals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'idempotency_key', name='uq_orders_idempotency')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)
        batch_op.create_index('ix_orders_open', ['account_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_symbol'), ['symbol'], unique=False)

    op.create_table('executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('slippage_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('realized_gain', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('realized_term', sa.String(length=8), nullable=True),
    sa.Column('wash_sale_disallowed', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('settles_on', sa.DateTime(), nullable=True),
    sa.Column('broker_execution_id', sa.String(length=80), nullable=True),
    sa.Column('venue', sa.String(length=32), nullable=False),
    sa.CheckConstraint("side IN ('BUY', 'SELL')", name='ck_executions_side'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_executions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_executed_at'), ['executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_symbol'), ['symbol'], unique=False)

    op.create_table('tax_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cost_per_share', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('disposed_at', sa.DateTime(), nullable=True),
    sa.Column('proceeds', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('realized_gain', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('term', sa.String(length=8), nullable=True),
    sa.Column('wash_sale_disallowed', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('replacement_lot_id', sa.Integer(), nullable=True),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("term IS NULL OR term IN ('short','long')", name='ck_tax_lots_term'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replacement_lot_id'], ['tax_lots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_lots_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_lots_acquired_at'), ['acquired_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_lots_id'), ['id'], unique=False)
        batch_op.create_index('ix_tax_lots_open', ['account_id', 'symbol', 'disposed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_lots_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_lots_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_lots_symbol'))
        batch_op.drop_index(batch_op.f('ix_tax_lots_org_id'))
        batch_op.drop_index('ix_tax_lots_open')
        batch_op.drop_index(batch_op.f('ix_tax_lots_id'))
        batch_op.drop_index(batch_op.f('ix_tax_lots_acquired_at'))
        batch_op.drop_index(batch_op.f('ix_tax_lots_account_id'))

    op.drop_table('tax_lots')
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_executions_symbol'))
        batch_op.drop_index(batch_op.f('ix_executions_org_id'))
        batch_op.drop_index(batch_op.f('ix_executions_order_id'))
        batch_op.drop_index(batch_op.f('ix_executions_id'))
        batch_op.drop_index(batch_op.f('ix_executions_executed_at'))
        batch_op.drop_index(batch_op.f('ix_executions_account_id'))

    op.drop_table('executions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_symbol'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_run_id'))
        batch_op.drop_index(batch_op.f('ix_orders_org_id'))
        batch_op.drop_index('ix_orders_open')
        batch_op.drop_index(batch_op.f('ix_orders_id'))
        batch_op.drop_index(batch_op.f('ix_orders_client_id'))
        batch_op.drop_index(batch_op.f('ix_orders_account_id'))

    op.drop_table('orders')
    with op.batch_alter_table('trade_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_proposals_run_id'))
        batch_op.drop_index(batch_op.f('ix_trade_proposals_org_id'))
        batch_op.drop_index(batch_op.f('ix_trade_proposals_id'))
        batch_op.drop_index(batch_op.f('ix_trade_proposals_client_id'))
        batch_op.drop_index(batch_op.f('ix_trade_proposals_account_id'))

    op.drop_table('trade_proposals')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_symbol'))
        batch_op.drop_index(batch_op.f('ix_positions_org_id'))
        batch_op.drop_index(batch_op.f('ix_positions_id'))
        batch_op.drop_index(batch_op.f('ix_positions_account_id'))

    op.drop_table('positions')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_org_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_client_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_as_of'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_account_id'))

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('cash_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_transactions_org_id'))
        batch_op.drop_index(batch_op.f('ix_cash_transactions_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_cash_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_cash_transactions_account_id'))

    op.drop_table('cash_transactions')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_org_id'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_id'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_client_id'))

    op.drop_table('risk_assessments')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_run_id'))
        batch_op.drop_index(batch_op.f('ix_reports_org_id'))
        batch_op.drop_index(batch_op.f('ix_reports_id'))
        batch_op.drop_index(batch_op.f('ix_reports_client_id'))

    op.drop_table('reports')
    with op.batch_alter_table('recommendation_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_outcomes_symbol'))
        batch_op.drop_index(batch_op.f('ix_recommendation_outcomes_run_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_outcomes_recommended_at'))
        batch_op.drop_index(batch_op.f('ix_recommendation_outcomes_org_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_outcomes_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_outcomes_client_id'))

    op.drop_table('recommendation_outcomes')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_run_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_queued_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_org_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_job_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_heartbeat_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_client_id'))
        batch_op.drop_index('ix_jobs_claim')

    op.drop_table('jobs')
    with op.batch_alter_table('investment_policies', schema=None) as batch_op:
        batch_op.drop_index('ix_policy_active')
        batch_op.drop_index(batch_op.f('ix_investment_policies_org_id'))
        batch_op.drop_index(batch_op.f('ix_investment_policies_id'))
        batch_op.drop_index(batch_op.f('ix_investment_policies_client_id'))

    op.drop_table('investment_policies')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_run_id'))
        batch_op.drop_index('ix_approvals_pending')
        batch_op.drop_index(batch_op.f('ix_approvals_org_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_client_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_org_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_id'))
        batch_op.drop_index('ix_agent_runs_client_time')
        batch_op.drop_index(batch_op.f('ix_agent_runs_client_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_org_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_client_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_clients_org_active')
        batch_op.drop_index(batch_op.f('ix_client_profiles_org_id'))
        batch_op.drop_index(batch_op.f('ix_client_profiles_name'))
        batch_op.drop_index(batch_op.f('ix_client_profiles_id'))
        batch_op.drop_index(batch_op.f('ix_client_profiles_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_client_profiles_advisor_id'))

    op.drop_table('client_profiles')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_org_time')
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_org_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_id'))

    op.drop_table('api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_org_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index('ix_users_email_lookup')

    op.drop_table('users')
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_securities_ticker'))
        batch_op.drop_index(batch_op.f('ix_securities_sector'))
        batch_op.drop_index('ix_securities_screen')
        batch_op.drop_index(batch_op.f('ix_securities_is_active'))
        batch_op.drop_index(batch_op.f('ix_securities_id'))
        batch_op.drop_index(batch_op.f('ix_securities_asset_class'))

    op.drop_table('securities')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    with op.batch_alter_table('market_data_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_data_cache_ticker'))
        batch_op.drop_index(batch_op.f('ix_market_data_cache_id'))
        batch_op.drop_index(batch_op.f('ix_market_data_cache_as_of_date'))

    op.drop_table('market_data_cache')
    # ### end Alembic commands ###
