"""Reserve cash on open buy orders

Revision ID: bffddbb4e18d
Revises: 3f8453b33b4d
Create Date: 2026-07-26 19:05:13.195213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bffddbb4e18d'
down_revision: Union[str, Sequence[str], None] = '3f8453b33b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved_cash', sa.Numeric(precision=18, scale=6), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('reserved_cash')

    # ### end Alembic commands ###
